AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A function that sells Habitica items periodically leaving only a subset of those

Globals:
  Function:
    Timeout: 15
    MemorySize: 128

Parameters:
  HabiticaApiKey:
    Type: String
    Description: The API key for the Habitica account
    NoEcho: true
  HabiticaUserId:
    Type: String
    Description: The user ID for the Habitica account
    NoEcho: true
  HabiticaTaskListBucketName:
    Type: String
    Description: The name of the S3 bucket for retrieving the Habitica task list
    Default: habitica-task-list-34s6n4781236n487

Resources:
  HabiticaSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Secret for the Habitica API key and user ID
      SecretString: !Sub '{"${HabiticaUserId}": "${HabiticaApiKey}"}'
  
  HabiticaSellItems:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sell_items/
      Handler: main.lambda_handler
      Runtime: python3.12
      Architectures:
        - arm64
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref HabiticaSecret
      Environment:
        Variables:
          HABITICA_SECRET: !Ref HabiticaSecret
          ITEMS_TO_LEAVE: "40"
      Events:
        FoodSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(10 1 * * ? *)
            Input: '{"sell_category": "food"}'
            Enabled: true
        EggsSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(15 1 * * ? *)
            Input: '{"sell_category": "eggs"}'
            Enabled: true
        HatchingPotionsSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(20 1 * * ? *)
            Input: '{"sell_category": "hatchingPotions"}'
            Enabled: true
  
  # Database and table for collecting Habitica statistics
  HabiticaStatsTimestream:
    Type: AWS::Timestream::Database
    Properties:
      DatabaseName: HabiticaStats

  HabiticaStatsTable:
    Type: AWS::Timestream::Table
    Properties:
      TableName: HabiticaStatsTable
      DatabaseName: !Ref HabiticaStatsTimestream
      RetentionProperties:
        MemoryStoreRetentionPeriodInHours: 168
        MagneticStoreRetentionPeriodInDays: 365

  HabiticaCollectStats:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: collect_stats/
      Handler: main.lambda_handler
      Runtime: python3.12
      Architectures:
        - arm64
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref HabiticaSecret
        - Statement:
            - Effect: Allow
              Action:
                - timestream:WriteRecords
                - timestream:DescribeTable
              Resource: !GetAtt HabiticaStatsTable.Arn
            - Effect: Allow
              Action:
                - timestream:DescribeEndpoints
              Resource: "*"
      Environment:
        Variables:
          HABITICA_SECRET: !Ref HabiticaSecret
          DATABASE_NAME: !Ref HabiticaStatsTimestream
          TABLE_NAME: !Select [ "1", !Split [ "|", !Ref HabiticaStatsTable ] ]
      Events:
        Schedule30Min:
          Type: Schedule
          Properties:
            Schedule: cron(*/30 * * * ? *)
            Enabled: true

  # Lambda for processing updated file and DynamoDB table to store the processed tasks. S3 bucket for storing the file
  HabiticaTaskListBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref HabiticaTaskListBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt HabiticaProcessTaskList.Arn
  
  HabiticaTaskListTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: HabiticaTaskList

  HabiticaProcessTaskList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: process_task_list/
      Handler: main.lambda_handler
      Runtime: python3.12
      Architectures:
        - arm64
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref HabiticaTaskListBucketName
        - DynamoDBCrudPolicy:
            TableName: !Ref HabiticaTaskListTable
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt HabiticaUpdateTasksStateMachine.Name
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref HabiticaSecret
      Environment:
        Variables:
          TABLE_NAME: !Ref HabiticaTaskListTable
          STEP_FUNCTION_NAME: !Ref HabiticaUpdateTasksStateMachine
          HABITICA_SECRET: !Ref HabiticaSecret
          TASK_TAG: 4aedf1fc-8dd7-4ff9-95f1-1f3112a0b815
  
  HabiticaProcessTaskListS3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt HabiticaProcessTaskList.Arn
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${HabiticaTaskListBucketName}"

  # Updating Habitica task list via Step Functions
  HabiticaUpdateTasksStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref HabiticaUpdateTasksLambda
      Definition:
        StartAt: Loop Tasks
        States:
          # Loop for all tasks
          Loop Tasks:
            Type: Choice
            Default: Succeed
            Choices:
              - Variable: "$.Finished"
                BooleanEquals: false
                Next: Update Task
          
          # Loop start
          Update Task:
            Type: Task
            Resource: !GetAtt HabiticaUpdateTasksLambda.Arn
            Parameters:
              List.$: "$.List"
              Finished: false
            Next: Wait
          
          Wait:
            Type: Wait
            Seconds: 2
            Next: Loop Tasks
          # Loop end

          Succeed:
            Type: Succeed
  
  HabiticaUpdateTasksLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_tasks/
      Handler: main.lambda_handler
      Runtime: python3.12
      Architectures:
        - arm64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HabiticaTaskListTable
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref HabiticaSecret
      Environment:
        Variables:
          HABITICA_SECRET: !Ref HabiticaSecret
          TABLE_NAME: !Ref HabiticaTaskListTable


Outputs:
  HabiticaStatsDatabaseName:
    Description: The database for storing Habitica statistics
    Value: !Ref HabiticaStatsTimestream
    Export:
      Name: HabiticaStatsDatabaseName
  
  HabiticaStatsTableName:
    Description: The table for storing Habitica statistics
    Value: !Select [ "1", !Split [ "|", !Ref HabiticaStatsTable ] ]
    Export:
      Name: HabiticaStatsTableName